/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2p2_kevinbanegas;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        cargarBinEmpleados();
        cargarBinCarros();
        tablaCarros();
        cbEmpleados();
        cbModCarros(carros);
        cbVerCarros();
        tablePagos();
        tableEntregados();
        tableEntregas();
        reparaciones();
        tableReparar();
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(30);
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(30);
        jTable2.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTable2.getColumnModel().getColumn(3).setPreferredWidth(30);
        jTable3.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable3.getColumnModel().getColumn(1).setPreferredWidth(30);
        jTable3.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTable3.getColumnModel().getColumn(3).setPreferredWidth(30);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        crud_empleados = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomEmpleado = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        carrosRep = new javax.swing.JTextField();
        edadEmpleado = new javax.swing.JSpinner();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        crud_carros = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        marcaCarro = new javax.swing.JTextField();
        modeloCarro = new javax.swing.JTextField();
        añofab = new javax.swing.JTextField();
        costoCarro = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        mod_carros = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        costoMod = new javax.swing.JSpinner();
        marcaMod = new javax.swing.JTextField();
        modeloMod = new javax.swing.JTextField();
        añoMod = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        simulacion = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jProgressBar1 = new javax.swing.JProgressBar();
        jComboBox3 = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        pagos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jToggleButton2 = new javax.swing.JToggleButton();
        entregas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jToggleButton3 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        reparaciones = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        crud_empleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        crud_empleados.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 126, -1, -1));

        jLabel2.setText("Edad");
        crud_empleados.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 270, -1, -1));

        jLabel3.setText("Numero de Identidad");
        crud_empleados.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 270, -1, -1));

        jLabel4.setText("Carros Reparados");
        crud_empleados.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 126, -1, -1));
        crud_empleados.add(nomEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 147, 98, -1));
        crud_empleados.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 291, 98, -1));
        crud_empleados.add(carrosRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 147, 89, -1));
        crud_empleados.add(edadEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 291, 98, -1));

        crud_empleados.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 146, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Eliminar Empleados");
        crud_empleados.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 146, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Empleados");
        crud_empleados.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 100, -1));

        jButton1.setText("Crear Emplelado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        crud_empleados.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 377, -1, 50));

        jButton2.setText("Eliminar Empleado");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        crud_empleados.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 150, 40));

        jTabbedPane1.addTab("Empleados", crud_empleados);

        crud_carros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Carros");
        crud_carros.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabel8.setText("Marca");
        crud_carros.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jLabel9.setText("Año Fabricacion");
        crud_carros.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        jLabel13.setText("Modelo");
        crud_carros.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jLabel15.setText("Costo");
        crud_carros.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Marca", "Modelo", "Estado de Reparacion", "Costo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        crud_carros.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 570, 150));
        crud_carros.add(marcaCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 100, -1));
        crud_carros.add(modeloCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 110, -1));
        crud_carros.add(añofab, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 120, -1));

        costoCarro.setModel(new SpinnerNumberModel(3000,3000,10000,500));
        crud_carros.add(costoCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 70, -1));

        jButton3.setText("Crear Carro");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        crud_carros.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        jTabbedPane2.addTab("Crear y Listar Carros", crud_carros);

        jLabel11.setText("Modificar Carros");

        jLabel12.setText("Marca");

        jLabel14.setText("Modelo");

        jLabel16.setText("Año Fabricación");

        jLabel17.setText("Costo");

        costoMod.setModel(new SpinnerNumberModel(3000,3000,10000,500));

        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });
        jComboBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox4MouseClicked(evt);
            }
        });
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jButton4.setText("Modificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mod_carrosLayout = new javax.swing.GroupLayout(mod_carros);
        mod_carros.setLayout(mod_carrosLayout);
        mod_carrosLayout.setHorizontalGroup(
            mod_carrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mod_carrosLayout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mod_carrosLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(mod_carrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mod_carrosLayout.createSequentialGroup()
                        .addGroup(mod_carrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(marcaMod, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(mod_carrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(modeloMod, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(mod_carrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(añoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mod_carrosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)))
                .addGroup(mod_carrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(costoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mod_carrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(285, 285, 285))
        );
        mod_carrosLayout.setVerticalGroup(
            mod_carrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mod_carrosLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(mod_carrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mod_carrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marcaMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeloMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(añoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Modificar Carros", mod_carros);

        jTabbedPane1.addTab("Carros", jTabbedPane2);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jToggleButton1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jToggleButton1.setText("Simular");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout simulacionLayout = new javax.swing.GroupLayout(simulacion);
        simulacion.setLayout(simulacionLayout);
        simulacionLayout.setHorizontalGroup(
            simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, simulacionLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, simulacionLayout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(simulacionLayout.createSequentialGroup()
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
        );
        simulacionLayout.setVerticalGroup(
            simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simulacionLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Simulación", simulacion);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Marca", "Modelo", "Estado de Reparación", "Costo"
            }
        ));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(2).setHeaderValue("Estado de Reparación");
        }

        jToggleButton2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jToggleButton2.setText("Pagar Carro");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pagosLayout = new javax.swing.GroupLayout(pagos);
        pagos.setLayout(pagosLayout);
        pagosLayout.setHorizontalGroup(
            pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagosLayout.createSequentialGroup()
                .addGroup(pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pagosLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pagosLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        pagosLayout.setVerticalGroup(
            pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pagos", pagos);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Marca", "Modelo", "Estado de Reparación", "Costo"
            }
        ));
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(2).setHeaderValue("Estado de Reparación");
        }

        jToggleButton3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jToggleButton3.setText("Entregar Carro");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout entregasLayout = new javax.swing.GroupLayout(entregas);
        entregas.setLayout(entregasLayout);
        entregasLayout.setHorizontalGroup(
            entregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entregasLayout.createSequentialGroup()
                .addGroup(entregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(entregasLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(entregasLayout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        entregasLayout.setVerticalGroup(
            entregasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entregasLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Entregas Pendientes", entregas);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Marca", "Modelo", "Costo de Reparar"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Entregados", jPanel2);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Empleado", "Cargo Reparar", "Exito"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        javax.swing.GroupLayout reparacionesLayout = new javax.swing.GroupLayout(reparaciones);
        reparaciones.setLayout(reparacionesLayout);
        reparacionesLayout.setHorizontalGroup(
            reparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reparacionesLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        reparacionesLayout.setVerticalGroup(
            reparacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reparacionesLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reparaciones", reparaciones);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 740, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Empleado e = new Empleado();
        e.setCarrosExito(Integer.parseInt(carrosRep.getText()));
        e.setCarrosRep(Integer.parseInt(id.getText()));
        e.setEdad(Integer.parseInt(edadEmpleado.getValue().toString()));
        e.setNombre(nomEmpleado.getText());

        empleados.add(e);

        System.out.println(empleados);
        ponerEmpleados();
        cargarBinEmpleados();
        cbEmpleados();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int indexEmp = jComboBox1.getSelectedIndex();
        empleados.remove(indexEmp);
        ponerEmpleados();
        cargarBinEmpleados();
        cbEmpleados();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Carro c = new Carro();
        c.setAño(Integer.parseInt(añofab.getText()));
        c.setCosto(Integer.parseInt(costoCarro.getValue().toString()));
        c.setEstado("En espera de entrar a reparación");
        c.setMarca(marcaCarro.getText());
        c.setModelo(modeloCarro.getText());

        carros.add(c);
        ArrayList<Carro> temp = new ArrayList();
        temp.addAll(carros);
        ponerCarros();
        cargarBinCarros();
        tablaCarros();
        tablePagos();
        cbModCarros(temp);
        cbVerCarros();
        System.out.println(carros);
        tablePagos();
        tablaCarros();
        tableEntregas();
        tableEntregados();
        JOptionPane.showMessageDialog(this, "Carro Creado", "Exito", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged

    }//GEN-LAST:event_jComboBox4ItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int index = jComboBox4.getSelectedIndex();
        Carro c = carros.get(index);
        c.setAño(Integer.parseInt(añoMod.getText()));
        c.setCosto(Integer.parseInt(costoMod.getValue().toString()));
        c.setMarca(marcaMod.getText());
        c.setModelo(modeloMod.getText());

        ArrayList<Carro> temp = new ArrayList();
        temp.addAll(carros);
        ponerCarros();
        cargarBinCarros();
        cbModCarros(temp);
        tablePagos();
        tablaCarros();
        tableEntregas();
        tableEntregados();
        JOptionPane.showMessageDialog(this, "Carro Modificado", "Exito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        tablaCarros();
        tableEntregados();
        tableEntregas();
        tablePagos();
        tableReparar();
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        Empleado e = ((Empleado) jComboBox2.getSelectedItem());
        int porcen = e.getPorcentaje();
        Reparado rep = new Reparado();
        Random r = new Random(100);
        int random = 0 + r.nextInt(100);
        String exito = "";
        Carro c = (Carro) jComboBox3.getSelectedItem();
        rep.setE(e);
        int costo = 0;
        for (Carro carro : carros) {
            if (c.equals(carro)) {
                costo = carro.getCosto();
                rep.setCargo(costo);
                if (porcen < random) {
                    rep.setExito("SI");
                    exito = "fue reparado con exito:";
                    carro.setEstado("En espera de pago de reparación");
                } else {
                    rep.setExito("NO");
                    exito = "no fue reparado con exito:";
                    carro.setEstado("En reparación");
                }
            }
        }
        reparado.add(rep);
        System.out.println(reparado);
        ponerReparar();
        reparaciones();
        System.out.println(reparado);
        bitacora(c, e, exito);
        ponerCarros();
        cargarBinCarros();
        cbVerCarros();
        tablePagos();
        tablaCarros();
        tableEntregas();
        tableEntregados();
        System.out.println(c.getEstado());
        Hilo h = new Hilo(costo, jProgressBar1, jLabel10, c);
        h.start();
        if (jProgressBar1.getValue() == costo / 1000) {
            jLabel10.setText("El carro esta " + c.getEstado());
        }


    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        if (jTable2.getSelectedRow() > -1) {
            String marca = jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString();
            String modelo = jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString();
            String costo = jTable2.getValueAt(jTable2.getSelectedRow(), 3).toString();
            for (Carro carro : carros) {
                if (carro.getMarca().equals(marca) && carro.getModelo().equals(modelo) && Integer.parseInt(costo) == carro.getCosto()) {
                    carro.setEstado("En espera a ser entregado");
                }
            }
            ponerCarros();
            cargarBinCarros();
            tablePagos();
            tablaCarros();
            JOptionPane.showMessageDialog(this, "Carro Entregado", "Exito", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        if (jTable3.getSelectedRow() > -1) {
            String marca = jTable3.getValueAt(jTable3.getSelectedRow(), 0).toString();
            String modelo = jTable3.getValueAt(jTable3.getSelectedRow(), 1).toString();
            String costo = jTable3.getValueAt(jTable3.getSelectedRow(), 3).toString();
            for (Carro carro : carros) {
                if (carro.getMarca().equals(marca) && carro.getModelo().equals(modelo) && Integer.parseInt(costo) == carro.getCosto()) {
                    carro.setEstado("Entregado");
                }
            }
            ponerCarros();
            cargarBinCarros();
            tablePagos();
            tablaCarros();
            tableEntregas();
            tableEntregados();
            JOptionPane.showMessageDialog(this, "Carro Entregado", "Exito", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jComboBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox4MouseClicked

    }//GEN-LAST:event_jComboBox4MouseClicked

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        if (jComboBox4.getSelectedIndex() > -1) {
            marcaMod.setText(((Carro) jComboBox4.getSelectedItem()).getMarca());
            modeloMod.setText(((Carro) jComboBox4.getSelectedItem()).getModelo());
            añoMod.setText("" + ((Carro) jComboBox4.getSelectedItem()).getAño());
            costoMod.setValue(((Carro) jComboBox4.getSelectedItem()).getCosto());
        }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    public void cargarBinEmpleados() {
        FileInputStream fis = null;
        ObjectInputStream ois = null;
        Empleado temp;
        emp = new File("./empleados.kev");
        try {
            empleados = new ArrayList();
            fis = new FileInputStream(emp);
            ois = new ObjectInputStream(fis);
            while ((temp = (Empleado) ois.readObject()) != null) {
                System.out.println(temp);
                empleados.add(temp);
            }
        } catch (Exception e) {
        }
        try {
            ois.close();
            fis.close();
        } catch (Exception e) {

        }
    }

    public void cargarBinCarros() {
        FileInputStream fis = null;
        ObjectInputStream ois = null;
        Carro temp;
        carr = new File("./carros.kev");
        try {
            carros = new ArrayList();
            fis = new FileInputStream(carr);
            ois = new ObjectInputStream(fis);
            while ((temp = (Carro) ois.readObject()) != null) {
                carros.add(temp);
            }
        } catch (Exception e) {
        }
        try {
            ois.close();
            fis.close();
        } catch (Exception e) {
        }

    }

    public void ponerCarros() {
        FileOutputStream fos = null;
        ObjectOutputStream oos = null;
        carr = new File("./carros.kev");
        try {
            fos = new FileOutputStream(carr);
            oos = new ObjectOutputStream(fos);
            for (Carro carro : carros) {
                oos.writeObject(carro);
            }
            oos.flush();
        } catch (Exception e) {
        }
        try {
            oos.close();
            fos.close();
        } catch (Exception e) {
        }
    }

    public void ponerEmpleados() {
        FileOutputStream fos = null;
        ObjectOutputStream oos = null;
        emp = new File("./empleados.kev");
        try {
            fos = new FileOutputStream(emp);
            oos = new ObjectOutputStream(fos);
            for (Empleado empleado : empleados) {
                oos.writeObject(empleado);
            }
            oos.flush();
        } catch (Exception e) {
        }
        try {
            oos.close();
            fos.close();
        } catch (Exception e) {
        }

    }

    public void tablaCarros() {
        DefaultTableModel tableM = (DefaultTableModel) jTable1.getModel();
        tableM.setNumRows(0);
        for (Carro carro : carros) {
            Object[] row = new Object[4];
            row[0] = carro.getMarca();
            row[1] = carro.getModelo();
            row[2] = carro.getEstado();
            row[3] = carro.getCosto();
            tableM.addRow(row);
        }
        jTable1.setModel(tableM);
    }

    public void cbEmpleados() {
        DefaultComboBoxModel cbM = (DefaultComboBoxModel) jComboBox1.getModel();
        cbM.removeAllElements();
        for (Empleado empleado : empleados) {
            cbM.addElement(empleado);
        }
        jComboBox1.setModel(cbM);
        jComboBox2.setModel(cbM);
    }

    public void cbModCarros(ArrayList<Carro> temp) {
        DefaultComboBoxModel cbM = (DefaultComboBoxModel) jComboBox4.getModel();
        cbM.removeAllElements();
        for (Carro carro : temp) {
            cbM.addElement(carro);
        }
        jComboBox4.setModel(cbM);
    }

    public void cbVerCarros() {
        DefaultComboBoxModel cbM = (DefaultComboBoxModel) jComboBox3.getModel();
        cbM.removeAllElements();
        for (Carro carro : carros) {
            if (carro.getEstado().equals("En espera de entrar a reparación") || carro.getEstado().equals("En espera de entrar a reparación")) {
                cbM.addElement(carro);
            }
        }
        jComboBox3.setModel(cbM);
    }

    public void bitacora(Carro c, Empleado em, String exito) {
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            fw = new FileWriter(bitac, true);
            bw = new BufferedWriter(fw);

            bw.write("El carro " + c.getModelo() + " " + exito + " en: " + new Date() + "\n");
            bw.flush();
        } catch (Exception e) {

        }
    }

    public void tablePagos() {
        DefaultTableModel tableM = (DefaultTableModel) jTable2.getModel();
        tableM.setNumRows(0);
        for (Carro carro : carros) {
            if ("En espera de pago de reparación".equals(carro.getEstado())) {
                Object[] row = new Object[4];
                row[0] = carro.getMarca();
                row[1] = carro.getModelo();
                row[2] = carro.getEstado();
                row[3] = carro.getCosto();
                tableM.addRow(row);
            }
        }
        jTable2.setModel(tableM);
    }

    public void tableEntregas() {
        DefaultTableModel tableM = (DefaultTableModel) jTable3.getModel();
        tableM.setNumRows(0);
        for (Carro carro : carros) {
            if ("En espera a ser entregado".equals(carro.getEstado())) {
                Object[] row = new Object[4];
                row[0] = carro.getMarca();
                row[1] = carro.getModelo();
                row[2] = carro.getEstado();
                row[3] = carro.getCosto();
                tableM.addRow(row);
            }
        }
        jTable3.setModel(tableM);
    }

    public void tableEntregados() {
        DefaultTableModel tableM = (DefaultTableModel) jTable4.getModel();
        tableM.setNumRows(0);
        for (Carro carro : carros) {
            if ("Entregado".equals(carro.getEstado())) {
                Object[] row = new Object[4];
                row[0] = carro.getMarca();
                row[1] = carro.getModelo();
                row[2] = carro.getCosto();
                tableM.addRow(row);
            }
        }
        jTable4.setModel(tableM);
    }

    public void reparaciones() {
        FileInputStream fis = null;
        ObjectInputStream ois = null;
        Reparado temp;
        reparacionesFile = new File("./reparaciones.kev");
        try {
            reparado = new ArrayList();
            fis = new FileInputStream(reparacionesFile);
            ois = new ObjectInputStream(fis);
            while ((temp = (Reparado) ois.readObject()) != null) {
                reparado.add(temp);
            }
        } catch (Exception e) {
        }
        try {
            ois.close();
            fis.close();
        } catch (Exception e) {
        }
    }

    public void tableReparar() {
        DefaultTableModel tableM = (DefaultTableModel) jTable5.getModel();
        tableM.setNumRows(0);
        for (Reparado rep : reparado) {
            Object[] row = new Object[3];
            row[0] = rep.getE();
            row[1] = rep.getCargo();
            row[2] = rep.getExito();
        }
        jTable5.setModel(tableM);
    }

    public void ponerReparar() {
        FileOutputStream fos = null;
        ObjectOutputStream oos = null;
        reparacionesFile = new File("./reparaciones.kev");
        try {
            fos = new FileOutputStream(reparacionesFile);
            oos = new ObjectOutputStream(fos);
            for (Reparado reparado1 : reparado) {
                oos.writeObject(reparado1);
            }
            oos.flush();
        } catch (Exception e) {
        }
        try {
            oos.close();
            fos.close();
        } catch (Exception e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    private ArrayList<Empleado> empleados = new ArrayList();
    private ArrayList<Carro> carros = new ArrayList();
    private ArrayList<Reparado> reparado = new ArrayList();
    private File emp = new File("./empleados.kev");
    private File carr = new File("./carros.kev");
    private File bitac = new File("./bitacora.txt");
    private File reparacionesFile = new File("./reparaciones.kev");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField añoMod;
    private javax.swing.JTextField añofab;
    private javax.swing.JTextField carrosRep;
    private javax.swing.JSpinner costoCarro;
    private javax.swing.JSpinner costoMod;
    private javax.swing.JPanel crud_carros;
    private javax.swing.JPanel crud_empleados;
    private javax.swing.JSpinner edadEmpleado;
    private javax.swing.JPanel entregas;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JTextField marcaCarro;
    private javax.swing.JTextField marcaMod;
    private javax.swing.JPanel mod_carros;
    private javax.swing.JTextField modeloCarro;
    private javax.swing.JTextField modeloMod;
    private javax.swing.JTextField nomEmpleado;
    private javax.swing.JPanel pagos;
    private javax.swing.JPanel reparaciones;
    private javax.swing.JPanel simulacion;
    // End of variables declaration//GEN-END:variables
}
